//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTracuu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTin
    {
        public int ID { get; set; }
        public string Nganh { get; set; }
        public string To_hop_thi { get; set; }
        public string Ma_nganh { get; set; }
        public Nullable<int> Chi_Tieu { get; set; }
        public string Tham_Gia_Doi_Tuyen { get; set; }
        public string To_Hop_XTT2 { get; set; }
        public string Ghi_Chu { get; set; }
        public string Loai_XT { get; set; }
        public Nullable<int> Ngoai_SP { get; set; }
    }
}
